### ISSUE TITLE
tag footer

### ISSUE THREAD

**Issue by devbeatriz** [iamgabrieloliveira/dev-blog#1]
Na linha 35 do arquivo [index.astro](https://github.com/iamgabrieloliveira/dev-blog/blob/main/src/pages/index.astro) a tag footer está fechada mas a mesma não foi aberta.

![footer tag](https://github.com/iamgabrieloliveira/dev-blog/assets/94017930/c0839300-2b15-4a72-8f11-b3d53ae3dec3)

**Comment by iamgabrieloliveira** [comment]
No html em si e em frameworks front end em geral que possuem conceito de componentes possuem [self closing tags](https://developer.mozilla.org/en-US/docs/Glossary/Void_element).

Nesse projeto eu usei o Framwork astro que usa como base o React, nesse caso o `Footer` não é a tag nativa do html e sim um componente.

É como se o trecho de código `<Footer />` fosse substituido pelo [conteúdo](https://github.com/iamgabrieloliveira/dev-blog/blob/main/src/components/Footer.astro) do componente.

O conteúdo da tag está dentre um arquivo separado, tem tags do html que possuem essa sintaxe, a tag `img` por exemplo.
